apiVersion: v1 
kind: Pod 
metadata:
  name: dynamic-pod 

spec:
containers:
    -  name: test-container 
       image: nginx
       volumeMounts:
         - mountPath: /test-pd 
           name: test-volume
volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: azure-managed-disk    